### ISSUE TITLE
Setting the Font on Windows

### ISSUE THREAD

**Issue by Squareys** [AravSinghal/ConsolasForPowerline#1]
Hi @AravSinghal !

Thank you for repatching Consolas 👍 I installed the font, but don't seem to be able to set it in my vimrc. I tried:

```
set guifont=Consolas\ for\ Powerline:h11
```

and

```
set guifont=ConsolasForPowerline:h11
```

At startup I get a error message "Invalid font" (in German). Am I missing something? Does the font name need to be different?

Thank you in advance.

Regards, Squareys.

**Comment by eviltak** [comment]
The font name is correct. Try using underscores instead of escaped spaces. I don't use `vim` (let alone `vim` on Windows), but on Linux `set guifont=Consolas\ for\ Powerline\ 11` works well. You might also want to try setting the font manually through the GUI and using `:set guifont?` to see what it should be in your _vimrc (escape all spaces).

**Comment by Squareys** [comment]
Thanks! I will try that.

**Comment by Squareys** [comment]
That works, by the way, sorry for the *huge* delay!
